from abc import ABC, abstractmethod
from fifo_tool_airlock_model_env.common.models import InferenceRequestContainerized

class LLMModel(ABC):
    """
    Abstract base class for model implementations.
    """

    @abstractmethod
    def load_model(self) -> None:
        """
        Load and initialize the model and its dependencies.
        """
        raise NotImplementedError

    @abstractmethod
    def generate(self, request: InferenceRequestContainerized) -> str:
        """
        Generate a response from a list of role-based messages.
        """
        raise NotImplementedError

    def _print_token_stats(self,
                           model_name: str,
                           adapter_name: str | None,
                           input_tokens: int,
                           output_tokens: int,
                           duration: float):
        """
        Print input/output token counts and generation time duration for a given model/adapter.

        Args:
            model_name (str):
                Name of the model

            adapter_name (str | None):
                Optional adapter name

            input_tokens (int):
                Number of tokens in the prompt.

            output_tokens (int):
                Number of tokens generated by the model.

            duration (float):
                Time in seconds taken to generate the response.
        """
        adapter = "[base model]" if adapter_name is None else f"[{adapter_name}]"
        print(f"📥 {input_tokens:>4} tokens in   ➜   📤 {output_tokens:>4} "
              f"tokens out   ⏱️ {duration:.2f}s    📦 {model_name}{adapter}")
